lockdown_start_at: 00:50
lockdown_end_at: 06:00
lock_screen: true
check_interval_seconds: 60
align_to_interval: true
force_screen_off_seconds: 3000
turn_on_screen_after_forced_off_period: true
lock_screen_command: loginctl lock-session
check_if_screen_is_off_command: xset q | grep 'Monitor is Off'
turn_off_screen_command: xset dpms force off
turn_on_screen_command: xset dpms force on
pause_media_command: playerctl --all-players pause
play_audio_notification_command: ffplay -nodisp -autoexit audio-notifications/goodnight-de.mp3 && ffplay -nodisp -autoexit audio-notifications/song.mp3
system_startup_readiness_check_command: xset q
display_ansi_time_for_tty: false
lockdown_override_codes:
  - tW2qtdnRxCljWsCDHltr
  - 38L7IZ8v5FJHacuSd24Z
  - HN8xrQRfigjn4j73Gx6j
  - Y6LPUzXAyOm6lTfxmw2I
  - C400xFK9HffwBf2iZ0GZ
  - 7NsFLcgzPO91kJmHvNkK
  - YWimpAt3S6AQMEvTnRB3
  - uBPooUMYb03o03S3HTQc
  - 8pGzrNDDmIRfJoZFBPg6
  - Lkb6znc404fe0fEopCBf
  - yaOHRGGemZEolJYaSziW
  - ZjEXEAq6loAKJ6GrrnVH
  - jwcvxLTcuJVUXUZTkADl
  - Ae9TBE7VZvzPmqrIjAw8
  - DzKj5e3wHnrYid15xbJS
  - KjUKgN1sxZ0iLuMWVaZF
  - ZpbcX6BbqRSfts1dx2k5
  - N8rOEFTMOJLUU69Zvbyh
  - Q5iTF1qoHTvr8y2MkSBq
  - RGdll5Gjlf6MLi24qWhG
