#!/bin/bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

set -x

ruby -r bundler/inline -e "
  gemfile(ui: true) do
    source 'https://rubygems.org'
    gem 'rainbow'
    gem 'image2ascii'
    gem 'rmagick'
  end
"

mkdir -p ~/.local/bin/
cp -f drowsier ~/.local/bin/

mkdir -p ~/.config/drowsier/

cp -f config.yaml ~/.config/drowsier/
cp -rf audio-notifications ~/.config/drowsier/

mkdir -p ~/.config/systemd/user/
cp -f systemd/drowsier.service ~/.config/systemd/user/

systemctl --user daemon-reload
systemctl enable --user drowsier
systemctl restart --user drowsier
systemctl status --user drowsier

# echo "Your new lockdown override codes:"
# ruby -r securerandom -e '20.times { puts SecureRandom.alphanumeric(20) }'
