#!/usr/bin/env ruby

require 'bundler/inline'

gemfile(ui: true) do
  source 'https://rubygems.org'
  gem 'awesome_print'
end

require 'awesome_print'
require 'yaml'

Dir.chdir(File.join(__dir__, '..'))

test_config_path = '/tmp/drowsier-config-test.yaml'
delay_seconds = 0
lockdown_duration_seconds = 2
lockdown_start_at = Time.now + delay_seconds
lockdown_end_at = lockdown_start_at + lockdown_duration_seconds

config = YAML.load(File.read('config.yaml'))
config.merge!(
  'lockdown_start_at' => lockdown_start_at.strftime('%H:%M:%S'),
  'lockdown_end_at' => lockdown_end_at.strftime('%H:%M:%S'),
  # 'lockdown_start_at' => '23:00',
  # 'lockdown_end_at' => '06:00',
  'lock_screen' => false,
  'check_interval_seconds' => 15,
  'align_to_interval' => false,
  'force_screen_off_seconds' => lockdown_duration_seconds,
  'turn_on_screen_after_forced_off_period' => true,
)
File.write(test_config_path, config.to_yaml)

ap config

cmd = "CONFIG=#{test_config_path} crystal run src/drowsier.cr --error-trace#{ARGV[0] && " -- " + ARGV[0]}"
puts "+ #{cmd}"
exec cmd
